### ISSUE TITLE
static_files as an env variable is not good for releases

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/cowboy-swagger#26]
Files in releases are placed under `lib/cowboy_swagger-…/…`.
The proper way to find that path would be:
```erlang
filename:join(code:priv_dir(cowboy_swagger), "swagger")
```

**Comment by cabol** [comment]
@elbrujohalcon we should discuss about this issue, if you take a look at the example code, there isn't any hack in code, the release was solved modifying the `relx.config` in order to copy the `priv/swagger` folder located in `cowboy-swagger`, to the `priv` directory of the app using cowboy-swagger. Check it out: https://github.com/inaka/cowboy-swagger/blob/master/example/relx.config#L7. I stay tuned.

**Comment by harenson** [comment]
@elbrujohalcon I tested it modifying the relx.config of serpents and it worked like a charm.

**Comment by elbrujohalcon** [comment]
@harenson @cabol that works, but you're forcing your users to modify their relx.config just to get swagger working in the first place. I would rather not require any special configuration from the user to get this library to _just work_. *If* the users want to apply his patches to the assets, then they can set the `static_files` environment parameter in their configuration. If they don't, cowboy swagger just automagically works. :star2:
