### ISSUE TITLE
Move from erlang.mk to rebar3

### ISSUE THREAD

**Issue by Euen** [inaka/cowboy-swagger#68]
Migrate to rebar3 as described [here](https://github.com/inaka/guidelines/blob/master/ERLANG.md#project-setup).

This is requested by esl/TODO#62

**Comment by hcs42** [comment]
@elbrujohalcon @Euen The swagger example still uses erlang.mk, and when I build it, it still uses the Makefile from cowboy-swagger. That Makefile it outdated, because it refers to [an old version of trails](https://github.com/inaka/cowboy-swagger/blob/2ae1e404fef89f716e8f418f3197a9801c53d751/Makefile#L11).

So when I build the cowboy-swagger example, it uses trails 0.1.1 instead of 0.2.0. This could be fixed by modifying the Makefile above. Shall I create a PR about that?

Also, this ticket is related: https://github.com/inaka/cowboy-swagger/issues/50 I think it can be closed, since the swagger example doesn't hardcode the trails version any more (the swagger Makefile does...)
